In [149]:
import csv
import json
import os

import pandas as pd
from pandas.io.json import json_normalize

In [150]:
os.chdir('C:\\Users\\dukho\\projects\\company sentiment\\data')
docs_file = '..\\docs.csv'
docs_headers = ['uuid', 'site','author', 'url', 'ord_in_thread', 'title','highlightText', 'language','text','published', 'crawled', 'highlightTitle']
orgs_file = '..\\orgs.csv'
orgs_headers = ['uuid','organization','sentiment']

### Creating csv with headers for 1st file with docs info

In [151]:
with open(docs_file,'w',encoding="utf-8",newline="") as csv_doc:
    writer = csv.DictWriter(csv_doc, fieldnames=docs_headers)
    writer.writeheader()

### Creating cwv with headers for 2nd file with organizations info

In [152]:
with open(orgs_file,'w',encoding="utf-8",newline="") as csv_org:
    writer = csv.DictWriter(csv_org, fieldnames=orgs_headers)
    writer.writeheader()

### Populating the data frame with document info

In [2]:
%%time

for dirpath, dirnames, files in os.walk('.'):
    for file_name in files:
        with open(os.path.join(dirpath,file_name), encoding="utf-8") as data_file:
            data = json.load(data_file)
            with open(docs_file,'a',encoding="utf-8",newline="") as csv_doc:
                writer = csv.DictWriter(csv_doc, fieldnames=docs_headers)
                writer.writerow({'uuid': data['uuid'],
                         'site': data['thread']['site'],
                         'author': data['author'],
                         'url': data['url'],
                         'ord_in_thread': data['ord_in_thread'],
                         'title': data['title'],
                         'highlightText': data['highlightText'], 
                         'language': data['language'],
                         'text': data['text'],
                         'published': data['published'], 
                         'crawled': data['crawled'], 
                         'highlightTitle': data['highlightTitle']                                      
                        })
        with open (orgs_file,'a',encoding="utf-8",newline="") as csv_org:
            writer_org = csv.DictWriter(csv_org, fieldnames=orgs_headers)
            for org in data['entities']['organizations']:
                writer_org.writerow({'uuid': data['uuid'],
                                     'organization': org['name'],
                                     'sentiment': org['sentiment']
                                    })

### Checking results

In [109]:
df = pd.read_csv(docs_file)

In [111]:
df.head()

,uuid,site,author,url,ord_in_thread,title,highlightText,language,text,published,crawled,highlightTitle
0,9d6d87d2c909b183527b26b8d991b69e5fe9b57f,cnbc.com,NaN,https://www.cnbc.com/2018/04/01/mexicos-andres...,0,Mexican presidential front-runner hits back at...,NaN,english,Mexico's presidential front-runner launched hi...,2018-04-02T00:47:00.000+03:00,2018-04-02T01:30:27.094+03:00,NaN
1,f3651238a13f24e8960f7ae87a1b08dad99557f4,cnbc.com,NaN,https://www.cnbc.com/2018/04/03/cbs-submits-be...,0,CBS submits below market value bid for VIACOM...,NaN,english,CBS has submitted a bid for Viacom that is bel...,2018-04-03T23:07:00.000+03:00,2018-04-03T23:10:36.004+03:00,NaN
2,da1e78e829cc34d67cef86ef80ec1cadbd394349,cnbc.com,NaN,https://www.cnbc.com/2018/04/03/nba-star-andre...,0,NBA star Andre Iguodala says his team's 'locke...,NaN,english,If you walk into the Golden State Warriors loc...,2018-04-03T21:40:00.000+03:00,2018-04-03T21:59:38.036+03:00,NaN
3,31f2bb1b0d2b384307e10235295c0606836c888a,fortune.com,Chris Morris,http://fortune.com/2018/04/03/snapchat-group-v...,0,Snapchat Introduces New Group Video Chat Feature,NaN,english,Snapchatâ€™s making it easier to hang out with f...,2018-04-03T18:13:00.000+03:00,2018-04-03T18:13:42.010+03:00,NaN
4,c9391abf20b441333ae03a54b39e90071dfb0988,cnbc.com,NaN,https://www.cnbc.com/video/2018/04/02/commodit...,0,Commodities tomorrow: Crude tumbles with stocks,NaN,english,Commodities tomorrow: Crude tumbles with stock...,2018-04-02T19:00:00.000+03:00,2018-04-03T04:23:21.008+03:00,NaN

In [112]:
df2 = pd.read_csv(orgs_file)

In [119]:
df2.head(100)

                                        uuid       name sentiment
0   9d6d87d2c909b183527b26b8d991b69e5fe9b57f      nafta  negative
1   9d6d87d2c909b183527b26b8d991b69e5fe9b57f        pri      none
2   f3651238a13f24e8960f7ae87a1b08dad99557f4     viacom  negative
3   f3651238a13f24e8960f7ae87a1b08dad99557f4        cbs  negative
4   f3651238a13f24e8960f7ae87a1b08dad99557f4       cnbc      none
..                                       ...        ...       ...
95  98e9feda3000e0ad9aa146896cd9d4711aab7875    reuters      none
96  98e9feda3000e0ad9aa146896cd9d4711aab7875   ak party      none
97  dbfc89a7d7a106615350bc8c71c3bc3ce577ebb9      apple  negative
98  dbfc89a7d7a106615350bc8c71c3bc3ce577ebb9  bloomberg  negative
99  dbfc89a7d7a106615350bc8c71c3bc3ce577ebb9      intel  negative

[100 rows x 3 columns]